import React from "react";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    inputStyle:{
        borderRadius:12,
        borderColor:'#BEBAB3',
        borderWidth:1,
        width:'90%',
        height:56,
        marginVertical:8,
        padding:16
    },
    titleStyle:{
      fontWeight:'500',
      fontSize:24,
      lineHeight:32,
      color:'#3C3A36',
      marginVertical:8,
      textAlign:'center',
    },
    opacityStyle:{
        marginVertical:8,
    },
    opacityStyleText:{
        fontSize:14, 
        fontWeight:"500", 
        color:'#78746D'
    },
    header:{
        justifyContent:'center',
        alignItems:'center',
        position:'absolute',
        width:'100%',
        height:55,
        top:44,
    },
    headerText:{
        fontWeight:'500',
        fontSize:24,
        lineHeight:32,
        textAlign:'center',
        paddingVertical:4,
        paddingLeft:'5%'
    },
    chooseCategoriesStyle:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        width:'90%',
        height:24,
        marginBottom:16,
    },
    tagstyle:{
        backgroundColor:'#65AAEA',
        borderRadius:12,
        alignItems:'center',
        marginHorizontal:4,
        paddingHorizontal:11,
        paddingVertical:3
    },
    tagTextStyle:{
        fontWeight:'500',
        fontSize:10,
        color: '#F2F2F2'
    },
    CourseCardContainer:{
        borderWidth:1, 
        borderColor:'#BEBAB3', 
        borderRadius:8, 
        display:"flex", 
        flexDirection:'column', 
        alignItems:'flex-start', 
        width:'90%', 
        height:275,
        marginBottom:20,
        alignSelf:'center',
        padding:8,
    },
    descriptionStyle:{
        fontSize:14,
        fontWeight:'400',
        color:'#3C3A36'
    },
    quizCounter:{
        fontSize:16,
        fontWeight:'400',
        color:'#78746D',
        textAlign:'center',
        marginTop:'25%'
    },
    questionTextStyle:{
        fontSize:24,
        fontWeight:'500',
        color:'#3C3A36',
        textAlign:'center',
        marginHorizontal:'5%',
    },
    testQuestionImageContainer:{
        width:'90%',
        alignSelf:'center',
        justifyContent:'center',
        alignItems:'center',
        paddingVertical:8,
        paddingHorizontal:16,
        borderColor:'#BEBAB3',
        borderRadius:8,
        borderWidth:1,
        marginVertical:'5%'
    },
    testQuestionImage:{
        width:311,
        height:175,
        borderRadius:8
    },
    testOptionStandardContainer:{
        width:'90%',
        borderColor:'#BEBAB3',
        borderWidth:1,
        borderRadius:8,
        paddingVertical:16,
        paddingHorizontal:24,
        alignSelf:'center',
        marginBottom:'5%'
    },
    testRightOptionContainer:{
        width:'90%',
        borderColor:'#5BA092',
        borderWidth:2,
        borderRadius:8,
        paddingVertical:16,
        paddingHorizontal:24,
        alignSelf:'center',
        marginBottom:'5%'
    },
    testWrongOptionContainer:{
        width:'90%',
        borderColor:'#EF4949',
        borderWidth:2,
        borderRadius:8,
        paddingVertical:16,
        paddingHorizontal:24,
        alignSelf:'center',
        marginBottom:'5%'
    },
    resultScoreStyle:{
        fontSize:56,
        fontWeight:'700',
        color:'#3C3A36',
        textAlign:'center',
        marginTop:'20%'
    },
    resultMessageStyle:{
        fontSize:24,
        fontWeight:'500',
        textAlign:'center',
        marginTop:'5%'
    },
    resultSubMessageStyle:{
        fontSize:14,
        fontWeight:'normal',
        color:'#78746D',
        textAlign:'center',
        marginTop:'2.5%',
    },
    configCellContainerStyle:{
        marginBottom:'5%', 
        borderColor:'#BEBAB3', 
        borderWidth:1, 
        borderRadius:16, 
        marginHorizontal:'5%', 
        flexDirection:'row',
        alignItems:'center',
        height:82
    },
    configImageContainer:{
        width:32, 
        height:32, 
        borderRadius:48, 
        backgroundColor:'#65AAEA', 
        justifyContent:'center', 
        alignItems:'center', 
        marginHorizontal:'5%'
    },
    configImage:{
        width:30, 
        height:28
    },
    configCellTitle:{
        fontSize:20,
        fontWeight:'500',
        color:'#3C3A36'
    },
    configCellInfo:{
        fontSize:14,
        fontWeight:'400',
        color:'#78746D'
    },
    configTextContainer:{
        width:'70%',
        justifyContent:'center',
    },
    nextIconImage:{
        width:8, 
        height:16
    },
    profileImageContainer:{
        width:172, 
        height:172, 
        padding:16, 
        justifyContent:'center', 
        alignItems:'center', 
        borderWidth:4, 
        borderColor:'#65AAEA', 
        borderRadius:100, 
        overflow:'hidden', 
        marginBottom:'10%'
    },
    profileImage:{
        width:155.22, 
        height:130.94, 
        resizeMode:'contain'
    },
    menuItem:{
        width:'90%',
        marginBottom:'5%',
        borderWidth:1,
        borderRadius:16,
        borderColor:'#BEBAB3',
        alignItems:'center',
        justifyContent:'center'
    },
    menuItemText:{
        fontSize:24,
        fontWeight:'500',
        color:'#3C3A36',
        marginVertical:24
    },
    aboutTitle:{
        fontWeight:'700',
        fontSize:40,
        color:'#3C3A36',
        marginTop:'5%'
    },
    aboutText:{
        fontSize:14,
        fontWeight:'400',
        color:'#78746D',
        textAlign:'center',
        marginTop:'7%'
    }
})

export default styles